name: 'Run Linter'
description: 'Run Linter'

inputs:
  os:
    description: "operating system"
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Python Packages (Linux)
      if: inputs.os == 'Linux'
      shell: bash
      run: |
        uv pip install --system flake8 pyproject-flake8 mypy
        uv pip install --system -r pyproject.toml --all-extras

    - name: Install Python Packages (Windows)
      if: inputs.os == 'Windows'
      shell: bash
      run: |
        uv pip install --system flake8 pyproject-flake8 mypy
        uv pip install --system -r pyproject.toml --extra graphblas --extra gui

    - name: Lint With flake8
      shell: bash
      run: |
        pflake8 .

    - name: Lint With MyPy (Linux)
      shell: bash
      if: inputs.os == 'Linux'
      # at the moment the ymq tests only support unix, so we exclude them on windows
      run: |
        mypy --install-types --non-interactive .


    - name: Lint With MyPy (Windows)
      shell: pwsh
      if: inputs.os == 'Windows'
      run: |
        mypy --install-types --non-interactive --exclude tests/cpp/ymq/py_mitm .
