// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: object_storage.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#ifndef CAPNP_VERSION
#error "CAPNP_VERSION is not defined, is capnp/generated-header-support.h missing?"
#elif CAPNP_VERSION != 1002000
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


CAPNP_BEGIN_HEADER

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(aee18e681cd62446);
CAPNP_DECLARE_SCHEMA(e64542cb4435845c);
enum class ObjectRequestType_e64542cb4435845c: uint16_t {
  SET_OBJECT,
  GET_OBJECT,
  DELETE_OBJECT,
  DUPLICATE_OBJECT_I_D,
  INFO_GET_TOTAL,
};
CAPNP_DECLARE_ENUM(ObjectRequestType, e64542cb4435845c);
CAPNP_DECLARE_SCHEMA(c7e1db63f7b4a37b);
CAPNP_DECLARE_SCHEMA(a18bfeeb4ed393d6);
CAPNP_DECLARE_SCHEMA(dd0b915af593a5b9);
enum class ObjectResponseType_dd0b915af593a5b9: uint16_t {
  SET_O_K,
  GET_O_K,
  DEL_O_K,
  DEL_NOT_EXISTS,
  DUPLICATE_O_K,
  INFO_GET_TOTAL_O_K,
};
CAPNP_DECLARE_ENUM(ObjectResponseType, dd0b915af593a5b9);

}  // namespace schemas
}  // namespace capnp

namespace scaler {
namespace protocol {

struct ObjectRequestHeader {
  ObjectRequestHeader() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  typedef ::capnp::schemas::ObjectRequestType_e64542cb4435845c ObjectRequestType;


  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(aee18e681cd62446, 3, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct ObjectID {
  ObjectID() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(c7e1db63f7b4a37b, 4, 0)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct ObjectResponseHeader {
  ObjectResponseHeader() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  typedef ::capnp::schemas::ObjectResponseType_dd0b915af593a5b9 ObjectResponseType;


  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(a18bfeeb4ed393d6, 3, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class ObjectRequestHeader::Reader {
public:
  typedef ObjectRequestHeader Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasObjectID() const;
  inline  ::scaler::protocol::ObjectID::Reader getObjectID() const;

  inline  ::uint64_t getPayloadLength() const;

  inline  ::uint64_t getRequestID() const;

  inline  ::scaler::protocol::ObjectRequestHeader::ObjectRequestType getRequestType() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class ObjectRequestHeader::Builder {
public:
  typedef ObjectRequestHeader Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasObjectID();
  inline  ::scaler::protocol::ObjectID::Builder getObjectID();
  inline void setObjectID( ::scaler::protocol::ObjectID::Reader value);
  inline  ::scaler::protocol::ObjectID::Builder initObjectID();
  inline void adoptObjectID(::capnp::Orphan< ::scaler::protocol::ObjectID>&& value);
  inline ::capnp::Orphan< ::scaler::protocol::ObjectID> disownObjectID();

  inline  ::uint64_t getPayloadLength();
  inline void setPayloadLength( ::uint64_t value);

  inline  ::uint64_t getRequestID();
  inline void setRequestID( ::uint64_t value);

  inline  ::scaler::protocol::ObjectRequestHeader::ObjectRequestType getRequestType();
  inline void setRequestType( ::scaler::protocol::ObjectRequestHeader::ObjectRequestType value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class ObjectRequestHeader::Pipeline {
public:
  typedef ObjectRequestHeader Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::scaler::protocol::ObjectID::Pipeline getObjectID();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class ObjectID::Reader {
public:
  typedef ObjectID Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline  ::uint64_t getField0() const;

  inline  ::uint64_t getField1() const;

  inline  ::uint64_t getField2() const;

  inline  ::uint64_t getField3() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class ObjectID::Builder {
public:
  typedef ObjectID Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::uint64_t getField0();
  inline void setField0( ::uint64_t value);

  inline  ::uint64_t getField1();
  inline void setField1( ::uint64_t value);

  inline  ::uint64_t getField2();
  inline void setField2( ::uint64_t value);

  inline  ::uint64_t getField3();
  inline void setField3( ::uint64_t value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class ObjectID::Pipeline {
public:
  typedef ObjectID Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class ObjectResponseHeader::Reader {
public:
  typedef ObjectResponseHeader Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasObjectID() const;
  inline  ::scaler::protocol::ObjectID::Reader getObjectID() const;

  inline  ::uint64_t getPayloadLength() const;

  inline  ::uint64_t getResponseID() const;

  inline  ::scaler::protocol::ObjectResponseHeader::ObjectResponseType getResponseType() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class ObjectResponseHeader::Builder {
public:
  typedef ObjectResponseHeader Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasObjectID();
  inline  ::scaler::protocol::ObjectID::Builder getObjectID();
  inline void setObjectID( ::scaler::protocol::ObjectID::Reader value);
  inline  ::scaler::protocol::ObjectID::Builder initObjectID();
  inline void adoptObjectID(::capnp::Orphan< ::scaler::protocol::ObjectID>&& value);
  inline ::capnp::Orphan< ::scaler::protocol::ObjectID> disownObjectID();

  inline  ::uint64_t getPayloadLength();
  inline void setPayloadLength( ::uint64_t value);

  inline  ::uint64_t getResponseID();
  inline void setResponseID( ::uint64_t value);

  inline  ::scaler::protocol::ObjectResponseHeader::ObjectResponseType getResponseType();
  inline void setResponseType( ::scaler::protocol::ObjectResponseHeader::ObjectResponseType value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class ObjectResponseHeader::Pipeline {
public:
  typedef ObjectResponseHeader Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::scaler::protocol::ObjectID::Pipeline getObjectID();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline bool ObjectRequestHeader::Reader::hasObjectID() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool ObjectRequestHeader::Builder::hasObjectID() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::scaler::protocol::ObjectID::Reader ObjectRequestHeader::Reader::getObjectID() const {
  return ::capnp::_::PointerHelpers< ::scaler::protocol::ObjectID>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::scaler::protocol::ObjectID::Builder ObjectRequestHeader::Builder::getObjectID() {
  return ::capnp::_::PointerHelpers< ::scaler::protocol::ObjectID>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::scaler::protocol::ObjectID::Pipeline ObjectRequestHeader::Pipeline::getObjectID() {
  return  ::scaler::protocol::ObjectID::Pipeline(_typeless.getPointerField(0));
}
#endif  // !CAPNP_LITE
inline void ObjectRequestHeader::Builder::setObjectID( ::scaler::protocol::ObjectID::Reader value) {
  ::capnp::_::PointerHelpers< ::scaler::protocol::ObjectID>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::scaler::protocol::ObjectID::Builder ObjectRequestHeader::Builder::initObjectID() {
  return ::capnp::_::PointerHelpers< ::scaler::protocol::ObjectID>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void ObjectRequestHeader::Builder::adoptObjectID(
    ::capnp::Orphan< ::scaler::protocol::ObjectID>&& value) {
  ::capnp::_::PointerHelpers< ::scaler::protocol::ObjectID>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::scaler::protocol::ObjectID> ObjectRequestHeader::Builder::disownObjectID() {
  return ::capnp::_::PointerHelpers< ::scaler::protocol::ObjectID>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline  ::uint64_t ObjectRequestHeader::Reader::getPayloadLength() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t ObjectRequestHeader::Builder::getPayloadLength() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void ObjectRequestHeader::Builder::setPayloadLength( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline  ::uint64_t ObjectRequestHeader::Reader::getRequestID() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t ObjectRequestHeader::Builder::getRequestID() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}
inline void ObjectRequestHeader::Builder::setRequestID( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS, value);
}

inline  ::scaler::protocol::ObjectRequestHeader::ObjectRequestType ObjectRequestHeader::Reader::getRequestType() const {
  return _reader.getDataField< ::scaler::protocol::ObjectRequestHeader::ObjectRequestType>(
      ::capnp::bounded<8>() * ::capnp::ELEMENTS);
}

inline  ::scaler::protocol::ObjectRequestHeader::ObjectRequestType ObjectRequestHeader::Builder::getRequestType() {
  return _builder.getDataField< ::scaler::protocol::ObjectRequestHeader::ObjectRequestType>(
      ::capnp::bounded<8>() * ::capnp::ELEMENTS);
}
inline void ObjectRequestHeader::Builder::setRequestType( ::scaler::protocol::ObjectRequestHeader::ObjectRequestType value) {
  _builder.setDataField< ::scaler::protocol::ObjectRequestHeader::ObjectRequestType>(
      ::capnp::bounded<8>() * ::capnp::ELEMENTS, value);
}

inline  ::uint64_t ObjectID::Reader::getField0() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t ObjectID::Builder::getField0() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void ObjectID::Builder::setField0( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline  ::uint64_t ObjectID::Reader::getField1() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t ObjectID::Builder::getField1() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}
inline void ObjectID::Builder::setField1( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS, value);
}

inline  ::uint64_t ObjectID::Reader::getField2() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t ObjectID::Builder::getField2() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}
inline void ObjectID::Builder::setField2( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, value);
}

inline  ::uint64_t ObjectID::Reader::getField3() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t ObjectID::Builder::getField3() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS);
}
inline void ObjectID::Builder::setField3( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS, value);
}

inline bool ObjectResponseHeader::Reader::hasObjectID() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool ObjectResponseHeader::Builder::hasObjectID() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::scaler::protocol::ObjectID::Reader ObjectResponseHeader::Reader::getObjectID() const {
  return ::capnp::_::PointerHelpers< ::scaler::protocol::ObjectID>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::scaler::protocol::ObjectID::Builder ObjectResponseHeader::Builder::getObjectID() {
  return ::capnp::_::PointerHelpers< ::scaler::protocol::ObjectID>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::scaler::protocol::ObjectID::Pipeline ObjectResponseHeader::Pipeline::getObjectID() {
  return  ::scaler::protocol::ObjectID::Pipeline(_typeless.getPointerField(0));
}
#endif  // !CAPNP_LITE
inline void ObjectResponseHeader::Builder::setObjectID( ::scaler::protocol::ObjectID::Reader value) {
  ::capnp::_::PointerHelpers< ::scaler::protocol::ObjectID>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::scaler::protocol::ObjectID::Builder ObjectResponseHeader::Builder::initObjectID() {
  return ::capnp::_::PointerHelpers< ::scaler::protocol::ObjectID>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void ObjectResponseHeader::Builder::adoptObjectID(
    ::capnp::Orphan< ::scaler::protocol::ObjectID>&& value) {
  ::capnp::_::PointerHelpers< ::scaler::protocol::ObjectID>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::scaler::protocol::ObjectID> ObjectResponseHeader::Builder::disownObjectID() {
  return ::capnp::_::PointerHelpers< ::scaler::protocol::ObjectID>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline  ::uint64_t ObjectResponseHeader::Reader::getPayloadLength() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t ObjectResponseHeader::Builder::getPayloadLength() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void ObjectResponseHeader::Builder::setPayloadLength( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline  ::uint64_t ObjectResponseHeader::Reader::getResponseID() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t ObjectResponseHeader::Builder::getResponseID() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}
inline void ObjectResponseHeader::Builder::setResponseID( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS, value);
}

inline  ::scaler::protocol::ObjectResponseHeader::ObjectResponseType ObjectResponseHeader::Reader::getResponseType() const {
  return _reader.getDataField< ::scaler::protocol::ObjectResponseHeader::ObjectResponseType>(
      ::capnp::bounded<8>() * ::capnp::ELEMENTS);
}

inline  ::scaler::protocol::ObjectResponseHeader::ObjectResponseType ObjectResponseHeader::Builder::getResponseType() {
  return _builder.getDataField< ::scaler::protocol::ObjectResponseHeader::ObjectResponseType>(
      ::capnp::bounded<8>() * ::capnp::ELEMENTS);
}
inline void ObjectResponseHeader::Builder::setResponseType( ::scaler::protocol::ObjectResponseHeader::ObjectResponseType value) {
  _builder.setDataField< ::scaler::protocol::ObjectResponseHeader::ObjectResponseType>(
      ::capnp::bounded<8>() * ::capnp::ELEMENTS, value);
}

}  // namespace
}  // namespace

CAPNP_END_HEADER

