import ast
import asyncio
import inspect
import os
import textwrap
import unittest
import unittest.mock
from pathlib import Path
from typing import Dict, List, Set, Tuple, get_args

from scaler.protocol.capnp import Task, TaskCancel, TaskCancelConfirmType, TaskResult, TaskResultType, TaskState
from scaler.scheduler.controllers import task_controller
from scaler.scheduler.controllers.task_controller import VanillaTaskController
from scaler.scheduler.task.task_event import TaskEvent
from scaler.scheduler.task.task_state_machine import TERMINAL_TASK_STATES
from scaler.utility.exceptions import SchedulerError
from scaler.utility.identifiers import TaskID
from scaler.utility.logging.utility import setup_logger
from scaler.utility.serialization import deserialize_failure
from tests.scheduler.controllers.task_state_graph_harness import (
    CLIENT_ID,
    LIVE_TASK_STATES,
    REJECTED,
    REPLACEMENT_WORKER_ID,
    SCENARIOS,
    TASK_ID,
    WORKER_ID,
    TaskControllerHarness,
    drive,
    make_task,
    make_task_cancel,
    make_task_cancel_confirm,
    make_task_result,
)
from tests.utility.utility import logging_test_name

SNAPSHOT_PATH = Path(__file__).parent / "task_state_graph.txt"
UPDATE_SNAPSHOT_ENVIRONMENT_VARIABLE = "SCALER_UPDATE_TASK_STATE_SNAPSHOT"

SNAPSHOT_HEADER = (
    "# The task state graph, derived by driving every (state, event) pair through the real router.\n"
    "# Generated by tests/scheduler/controllers/test_task_controller.py, do not edit by hand.\n"
    f"# Regenerate with {UPDATE_SNAPSHOT_ENVIRONMENT_VARIABLE}=1 python -m unittest"
    " tests.scheduler.controllers.test_task_controller\n"
    "#\n"
    "# Only live states are sources: a terminal state removes the machine, so no event can reach one.\n"
)

SOURCE_COLUMN_WIDTH = 17
SCENARIO_COLUMN_WIDTH = 38


def format_snapshot_line(source_name: str, scenario_name: str, target_name: str) -> str:
    return f"{source_name:<{SOURCE_COLUMN_WIDTH}} {scenario_name:<{SCENARIO_COLUMN_WIDTH}} -> {target_name}"


def parse_snapshot(text: str) -> List[Tuple[str, str, str]]:
    rows = []
    for line in text.splitlines():
        if not line.strip() or line.startswith("#"):
            continue

        left, target_name = line.split("->")
        source_name, scenario_name = left.split(None, 1)
        rows.append((source_name, scenario_name.strip(), target_name.strip()))

    return rows


async def build_snapshot_rows() -> List[Tuple[str, str, str]]:
    rows = []
    for source in LIVE_TASK_STATES:
        for scenario in SCENARIOS:
            target_name = await drive(TaskControllerHarness(), source, scenario)
            rows.append((source.name, scenario.name, target_name))

    return rows


class TestTaskStateGraph(unittest.IsolatedAsyncioTestCase):
    """Section 7: the graph snapshot and the reachability checks that read it."""

    def setUp(self) -> None:
        setup_logger()
        logging_test_name(self)

    async def test_graph_snapshot_matches_the_checked_in_file(self):
        """Every legal pair reaches its action and raises nothing, and the graph it describes is the recorded one."""

        rows = await build_snapshot_rows()
        snapshot = SNAPSHOT_HEADER + "".join(
            format_snapshot_line(source_name, scenario_name, target_name) + "\n"
            for source_name, scenario_name, target_name in rows
        )

        if os.environ.get(UPDATE_SNAPSHOT_ENVIRONMENT_VARIABLE):
            SNAPSHOT_PATH.write_text(snapshot)
            self.skipTest(f"rewrote {SNAPSHOT_PATH}")

        self.assertEqual(
            snapshot.splitlines(),
            SNAPSHOT_PATH.read_text().splitlines(),
            f"the routing behavior changed, rerun with {UPDATE_SNAPSHOT_ENVIRONMENT_VARIABLE}=1 to record it",
        )

    def test_every_state_is_reachable_from_inactive(self):
        edges = self.__snapshot_edges()

        reachable = {TaskState.inactive.name}
        pending = [TaskState.inactive.name]
        while pending:
            source_name = pending.pop()
            for target_name in edges.get(source_name, set()):
                if target_name not in reachable:
                    reachable.add(target_name)
                    pending.append(target_name)

        self.assertEqual(reachable, {state.name for state in TaskState})

    def test_every_live_state_reaches_a_terminal_state(self):
        edges = self.__snapshot_edges()
        terminal_names = {state.name for state in TERMINAL_TASK_STATES}

        for source in LIVE_TASK_STATES:
            reachable: Set[str] = set()
            pending = [source.name]
            while pending:
                source_name = pending.pop()
                for target_name in edges.get(source_name, set()):
                    if target_name not in reachable:
                        reachable.add(target_name)
                        pending.append(target_name)

            self.assertTrue(
                reachable & terminal_names, f"{source.name} cannot reach a terminal state, its task would be stranded"
            )

    async def test_terminal_states_reject_every_event(self):
        for source in TERMINAL_TASK_STATES:
            for scenario in SCENARIOS:
                with self.subTest(source=source.name, scenario=scenario.name):
                    harness = TaskControllerHarness()
                    state_machine = await harness.enter_state(TaskState.running)
                    state_machine.commit("setup", source)
                    harness.apply(scenario)

                    path_before = state_machine.get_path()
                    await harness.route(scenario.event)

                    self.assertEqual(state_machine.get_path(), path_before)

    def __snapshot_edges(self) -> Dict[str, Set[str]]:
        edges: Dict[str, Set[str]] = {}
        for source_name, _, target_name in parse_snapshot(SNAPSHOT_PATH.read_text()):
            if target_name == REJECTED:
                continue

            edges.setdefault(source_name, set()).add(target_name)

        return edges


class TestTaskControllerRouter(unittest.TestCase):
    """Section 7: the router dispatches on the event class, and every event class has exactly one arm."""

    def setUp(self) -> None:
        self.__arms = self.__parse_router_arms()

    def test_every_event_class_has_a_router_arm(self):
        self.assertEqual(set(self.__arms), {event_class.__name__ for event_class in get_args(TaskEvent)})

    def test_every_router_arm_calls_a_distinct_action(self):
        self.assertEqual(len(set(self.__arms.values())), len(self.__arms))

        for event_name, action_name in self.__arms.items():
            with self.subTest(event=event_name):
                self.assertTrue(hasattr(VanillaTaskController, f"_VanillaTaskController{action_name}"))

    def test_the_router_is_exhaustive_over_the_event_union(self):
        match_node = self.__find_router_match()
        wildcard_bodies = [
            case.body
            for case in match_node.cases
            if isinstance(case.pattern, ast.MatchAs) and case.pattern.pattern is None
        ]

        self.assertEqual(len(wildcard_bodies), 1, "the router needs one wildcard arm to make the match exhaustive")
        self.assertIn("assert_never", ast.dump(wildcard_bodies[0][0]))

    @staticmethod
    def __find_router_match() -> ast.Match:
        source = textwrap.dedent(inspect.getsource(VanillaTaskController._VanillaTaskController__route))  # type: ignore[attr-defined]  # noqa: E501
        match_nodes = [
            node
            for node in ast.walk(ast.parse(source))
            if isinstance(node, ast.Match) and isinstance(node.subject, ast.Name) and node.subject.id == "event"
        ]

        assert len(match_nodes) == 1, "the router must dispatch on exactly one match over the event"
        return match_nodes[0]

    @classmethod
    def __parse_router_arms(cls) -> Dict[str, str]:
        arms = {}
        for case in cls.__find_router_match().cases:
            if not isinstance(case.pattern, ast.MatchClass) or not isinstance(case.pattern.cls, ast.Name):
                continue

            called = [
                node.func.attr
                for node in ast.walk(ast.Module(body=case.body, type_ignores=[]))
                if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute)
            ]
            assert len(called) == 1, f"the arm of {case.pattern.cls.id} must call exactly one action"
            arms[case.pattern.cls.id] = called[0]

        return arms


class TestTaskControllerBehavior(unittest.IsolatedAsyncioTestCase):
    """Section 4: the defects that moving the actions onto the transitions resolves."""

    def setUp(self) -> None:
        setup_logger()
        logging_test_name(self)
        self.harness = TaskControllerHarness()

    async def test_worker_disconnect_while_canceling_confirms_the_cancel_to_the_client(self):
        """Section 4.1: this pair used to bind the wrong payload and raise TypeError before the action ever ran."""

        await self.harness.enter_state(TaskState.canceling)

        await self.harness.controller.on_worker_disconnect(TASK_ID, WORKER_ID)

        confirms = self.harness.cancel_confirms_sent_to(CLIENT_ID)
        self.assertEqual(len(confirms), 1)
        self.assertEqual(TaskCancelConfirmType(confirms[0].cancelConfirmType.value), TaskCancelConfirmType.canceled)
        self.assertIsNone(self.harness.get_state_machine())

    async def test_worker_disconnect_while_canceling_releases_worker_capacity_once(self):
        """Section 4.3: remove_worker already released the capacity, so the action must not release it again."""

        await self.harness.enter_state(TaskState.canceling)

        await self.harness.controller.on_worker_disconnect(TASK_ID, WORKER_ID)

        self.harness.worker_controller.on_task_done.assert_not_awaited()

    async def test_balance_cancel_confirm_not_found_strands_the_task(self):
        """The restructure preserves this hole, it does not fix it.

        The recovery is a behavior change that needs its own review, so the arm returns None and the task keeps the
        dead end it has on main. Replace this test when the follow-up decides between terminating and rescheduling.
        """

        state_machine = await self.harness.enter_state(TaskState.balanceCanceling)

        await self.harness.controller.on_task_cancel_confirm(
            make_task_cancel_confirm(TaskCancelConfirmType.cancelNotFound)
        )

        self.assertEqual(state_machine.current_state(), TaskState.balanceCanceling)
        self.assertIsNotNone(self.harness.get_state_machine())
        self.harness.worker_controller.on_task_done.assert_not_awaited()
        self.assertEqual(len(self.harness.messages_sent_to(CLIENT_ID)), 0)

    async def test_balance_cancel_without_a_worker_strands_the_task(self):
        """The same preserved hole, reached from the scheduler side instead of from a worker message."""

        state_machine = await self.harness.enter_state(TaskState.running)
        self.harness.set_worker_holds_task(False)

        await self.harness.controller.on_task_balance_cancel(TASK_ID)

        self.assertEqual(state_machine.current_state(), TaskState.balanceCanceling)
        self.assertIsNotNone(self.harness.get_state_machine())
        self.assertEqual(len(self.harness.messages_sent_to(CLIENT_ID)), 0)

    async def test_balance_cancel_confirm_canceled_reschedules_the_task(self):
        state_machine = await self.harness.enter_state(TaskState.balanceCanceling)
        self.harness.set_capacity_available(True)

        await self.harness.controller.on_task_cancel_confirm(make_task_cancel_confirm(TaskCancelConfirmType.canceled))

        self.assertEqual(state_machine.current_state(), TaskState.running)
        self.harness.worker_controller.on_task_done.assert_awaited_once_with(TASK_ID)
        self.assertEqual(len(self.harness.messages_sent_to(REPLACEMENT_WORKER_ID)), 1)

    async def test_balance_cancel_confirm_canceled_queues_the_task_when_no_worker_is_free(self):
        state_machine = await self.harness.enter_state(TaskState.balanceCanceling)
        self.harness.set_capacity_available(False)

        await self.harness.controller.on_task_cancel_confirm(make_task_cancel_confirm(TaskCancelConfirmType.canceled))

        self.assertEqual(state_machine.current_state(), TaskState.inactive)
        self.assertEqual(self.harness.messages_sent_to(REPLACEMENT_WORKER_ID), [])

    async def test_cancel_confirm_failed_keeps_the_task_running(self):
        """The worker refused the cancel, so the scheduler waits for the real result and sends nothing."""

        state_machine = await self.harness.enter_state(TaskState.canceling)

        await self.harness.controller.on_task_cancel_confirm(
            make_task_cancel_confirm(TaskCancelConfirmType.cancelFailed)
        )

        self.assertEqual(state_machine.current_state(), TaskState.running)
        self.harness.binder.send.assert_not_awaited()
        self.harness.worker_controller.on_task_done.assert_not_awaited()

    async def test_task_cancel_while_balance_canceling_does_not_send_a_second_cancel(self):
        state_machine = await self.harness.enter_state(TaskState.balanceCanceling)

        await self.harness.controller.on_task_cancel(CLIENT_ID, make_task_cancel())

        self.assertEqual(state_machine.current_state(), TaskState.canceling)
        self.harness.worker_controller.on_task_cancel.assert_not_awaited()
        self.harness.binder.send.assert_not_awaited()

    async def test_task_cancel_while_inactive_confirms_and_drops_the_queued_task(self):
        state_machine = await self.harness.enter_state(TaskState.inactive)

        await self.harness.controller.on_task_cancel(CLIENT_ID, make_task_cancel())

        self.assertEqual(state_machine.current_state(), TaskState.canceled)
        self.harness.worker_controller.on_task_done.assert_not_awaited()
        self.assertEqual(len(self.harness.messages_sent_to(CLIENT_ID)), 1)
        self.assertEqual(list(self.harness.controller._unassigned), [])

    async def test_task_cancel_without_a_worker_reports_not_found(self):
        state_machine = await self.harness.enter_state(TaskState.running)
        self.harness.set_worker_holds_task(False)

        await self.harness.controller.on_task_cancel(CLIENT_ID, make_task_cancel())

        self.assertEqual(state_machine.current_state(), TaskState.canceledNotFound)
        confirms = self.harness.cancel_confirms_sent_to(CLIENT_ID)
        self.assertEqual(len(confirms), 1)
        self.assertEqual(
            TaskCancelConfirmType(confirms[0].cancelConfirmType.value), TaskCancelConfirmType.cancelNotFound
        )

    async def test_each_task_result_type_reaches_its_own_terminal_state(self):
        for result_type, expected in (
            (TaskResultType.success, TaskState.success),
            (TaskResultType.failed, TaskState.failed),
            (TaskResultType.failedWorkerDied, TaskState.failedWorkerDied),
        ):
            with self.subTest(result_type=result_type.name):
                harness = TaskControllerHarness()
                state_machine = await harness.enter_state(TaskState.running)

                await harness.controller.on_task_result(make_task_result(result_type))

                self.assertEqual(state_machine.current_state(), expected)
                self.assertIsNone(harness.get_state_machine())
                self.assertEqual(len(harness.task_results_sent_to(CLIENT_ID)), 1)

    async def test_a_duplicate_worker_disconnect_is_ignored(self):
        """Racing duplicates are normal, the second one must not reroute the task a second time."""

        state_machine = await self.harness.enter_state(TaskState.running)
        self.harness.set_capacity_available(True)

        await self.harness.controller.on_worker_disconnect(TASK_ID, WORKER_ID)
        self.assertEqual(state_machine.current_state(), TaskState.running)
        self.assertEqual(len(self.harness.messages_sent_to(REPLACEMENT_WORKER_ID)), 1)

        state_machine.commit("setup", TaskState.canceled)
        await self.harness.controller.on_worker_disconnect(TASK_ID, WORKER_ID)
        self.assertEqual(state_machine.current_state(), TaskState.canceled)

    async def test_the_monitor_reports_the_state_that_the_task_lands_in(self):
        await self.harness.enter_state(TaskState.running)

        await self.harness.controller.on_task_result(make_task_result(TaskResultType.success))

        self.assertEqual(self.harness.monitored_task_states(), [TaskState.success])

    async def test_an_event_for_an_unknown_task_is_dropped(self):
        await self.harness.controller.on_task_result(make_task_result(TaskResultType.success))

        self.harness.binder.send.assert_not_awaited()

    async def test_an_action_that_raises_does_not_escape_the_router(self):
        """The router logs and swallows, so one failed task cannot stop a timer loop or a message handler."""

        await self.harness.enter_state(TaskState.canceling)
        self.harness.worker_controller.on_task_done.side_effect = RuntimeError("the action failed")

        await self.harness.controller.on_task_cancel_confirm(make_task_cancel_confirm(TaskCancelConfirmType.canceled))

    async def test_an_action_that_raises_fails_the_task_to_its_client(self):
        """Section 5.3: the transition is never committed, so the task is terminated rather than left mid-flight."""

        await self.harness.enter_state(TaskState.canceling)
        self.harness.worker_controller.on_task_done.side_effect = RuntimeError("the action failed")

        await self.harness.controller.on_task_cancel_confirm(make_task_cancel_confirm(TaskCancelConfirmType.canceled))

        self.assertIsNone(self.harness.get_state_machine(), "a faulted task must not stay live")

        results = self.harness.task_results_sent_to(CLIENT_ID)
        self.assertEqual(len(results), 1, "the client is told the task failed")
        self.assertEqual(TaskResultType(results[0].resultType.value), TaskResultType.failed)

        self.harness.connector_storage.set_object.assert_awaited_once()
        payload = self.harness.connector_storage.set_object.await_args.args[1]
        self.assertIsInstance(deserialize_failure(payload), SchedulerError)

    async def test_a_faulted_teardown_still_does_not_escape_the_router(self):
        """The teardown runs from the router's except, so its own failure must not propagate either."""

        await self.harness.enter_state(TaskState.canceling)
        self.harness.worker_controller.on_task_done.side_effect = RuntimeError("the action failed")
        self.harness.connector_storage.set_object.side_effect = RuntimeError("object storage is down")

        await self.harness.controller.on_task_cancel_confirm(make_task_cancel_confirm(TaskCancelConfirmType.canceled))

        self.assertIsNone(self.harness.get_state_machine(), "the machine is dropped even when the teardown fails")


class TestTaskStateExclusion(unittest.IsolatedAsyncioTestCase):
    """Section 3.4 and 3.5: one task's transitions are serialized, so two events cannot both act on one machine."""

    def setUp(self) -> None:
        setup_logger()
        logging_test_name(self)
        self.harness = TaskControllerHarness()

    async def test_two_events_for_one_task_do_not_both_transition_it(self):
        """Without the lock this commits running -> running and running -> success on the same machine.

        The client is told the task succeeded and the same task is handed to a second worker, which is the duplicate
        execution of section 5.1 arriving through a different door.
        """

        state_machine = await self.harness.enter_state(TaskState.running)

        in_send = asyncio.Event()
        release = asyncio.Event()
        committed: List[str] = []

        async def blocking_send(peer, message, detached=False):
            if isinstance(message, TaskResult):
                committed.append("result delivered to client")
                in_send.set()
                await release.wait()
            elif isinstance(message, Task):
                committed.append("task rerouted to another worker")

        self.harness.binder.send.side_effect = blocking_send

        first = asyncio.create_task(self.harness.controller.on_task_result(make_task_result(TaskResultType.success)))
        await in_send.wait()

        # a heartbeat timeout fires for the same task while its result is still being sent
        second = asyncio.create_task(self.harness.controller.on_worker_disconnect(TASK_ID, WORKER_ID))
        await asyncio.sleep(0)
        release.set()
        await asyncio.gather(first, second)

        self.assertEqual(committed, ["result delivered to client"], "the disconnect must not also act")
        self.assertEqual(state_machine.current_state(), TaskState.success)
        self.assertIsNone(self.harness.get_state_machine())

    async def test_an_event_that_arrives_while_the_task_finishes_is_dropped(self):
        """The second event waits on the lock, then finds that the machine it locked is no longer the registered one."""

        await self.harness.enter_state(TaskState.running)

        in_send = asyncio.Event()
        release = asyncio.Event()

        async def blocking_send(peer, message, detached=False):
            if isinstance(message, TaskResult):
                in_send.set()
                await release.wait()

        self.harness.binder.send.side_effect = blocking_send

        first = asyncio.create_task(self.harness.controller.on_task_result(make_task_result(TaskResultType.success)))
        await in_send.wait()

        second = asyncio.create_task(self.harness.controller.on_task_cancel(CLIENT_ID, make_task_cancel()))
        await asyncio.sleep(0)
        release.set()
        await asyncio.gather(first, second)

        self.assertEqual(len(self.harness.cancel_confirms_sent_to(CLIENT_ID)), 0, "the cancel must not be answered")

    async def test_a_cycle_in_the_lock_order_degrades_to_a_logged_drop(self):
        """Section 3.5.2: the acquire timeout is what bounds a deadlock, so it must be reachable.

        A terminal transition fans out to other tasks, so it takes a second task's lock while holding its own. That is
        safe only because the acquisition graph has no cycle, which rests on two guards in
        ``VanillaGraphTaskController.__cancel_whole_graph``. This builds the cycle those guards prevent, with both
        tasks forced to hold their own lock before either reaches for the other, and asserts that the scheduler
        reports it and continues instead of hanging forever.
        """

        first_task_id = TaskID(b"graph-sibling-one")
        second_task_id = TaskID(b"graph-sibling-two")

        await self.harness.controller.on_task_new(make_task(first_task_id))
        await self.harness.controller.on_task_new(make_task(second_task_id))

        sibling_of = {first_task_id: second_task_id, second_task_id: first_task_id}
        both_are_inside_their_own_lock = asyncio.Event()
        arrived = 0

        async def cancel_the_sibling(task_result: TaskResult) -> None:
            nonlocal arrived
            arrived += 1
            if arrived == 2:
                both_are_inside_their_own_lock.set()
            await both_are_inside_their_own_lock.wait()

            sibling = sibling_of[TaskID(task_result.taskId)]
            await self.harness.controller.on_task_cancel(
                CLIENT_ID, TaskCancel(taskId=sibling, flags=TaskCancel.TaskCancelFlags(force=True))
            )

        self.harness.graph_controller.is_graph_subtask.return_value = True
        self.harness.graph_controller.on_graph_sub_task_result.side_effect = cancel_the_sibling

        with unittest.mock.patch.object(task_controller, "LOCK_ACQUIRE_TIMEOUT_SECONDS", 0.1):
            with self.assertLogs("scaler.scheduler.controllers.task_controller", level="ERROR") as logs:
                await asyncio.wait_for(
                    asyncio.gather(
                        self.harness.controller.on_task_result(
                            TaskResult(
                                taskId=first_task_id, resultType=TaskResultType.success, metadata=b"", results=[]
                            )
                        ),
                        self.harness.controller.on_task_result(
                            TaskResult(
                                taskId=second_task_id, resultType=TaskResultType.success, metadata=b"", results=[]
                            )
                        ),
                    ),
                    timeout=5,
                )

        self.assertTrue(
            any("lock not acquired" in line for line in logs.output),
            "a lock that cannot be taken must name the task and its debug path",
        )

    async def test_the_lock_is_released_when_an_action_raises(self):
        """A swallowed exception that also stranded the lock would deadlock every later event for that task."""

        state_machine = await self.harness.enter_state(TaskState.canceling)
        self.harness.worker_controller.on_task_done.side_effect = RuntimeError("the action failed")

        await self.harness.controller.on_task_cancel_confirm(make_task_cancel_confirm(TaskCancelConfirmType.canceled))

        self.assertFalse(state_machine.lock.locked(), "the lock must not survive a faulted transition")


class TestTaskControllerStatistics(unittest.IsolatedAsyncioTestCase):
    def setUp(self) -> None:
        setup_logger()
        logging_test_name(self)

    async def test_the_status_covers_every_task_state(self):
        harness = TaskControllerHarness()
        status = harness.controller.get_status()

        self.assertEqual({TaskState(pair.state) for pair in status.stateToCount}, set(TaskState))

    async def test_a_finished_task_leaves_no_state_behind(self):
        harness = TaskControllerHarness()
        await harness.controller.on_task_new(make_task())
        await harness.controller.on_task_result(make_task_result(TaskResultType.success))

        self.assertIsNone(harness.get_state_machine())
        self.assertNotIn(TASK_ID, harness.controller._task_id_to_task)
        self.assertEqual(list(harness.controller._unassigned), [])


if __name__ == "__main__":
    unittest.main()
