name: 'Run Tests With Wheel Installed'
description: 'Run Unit Tests And Examples With Wheel Installed'

inputs:
  os:
    description: "operating system"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install dependencies for MITM tests
      if: inputs.os == 'Linux'
      shell: bash
      run: uv pip install --system scapy==2.*

    - name: Run C++ Tests (Linux)
      if: inputs.os == 'Linux'
      shell: bash
      run: sudo ./scripts/test.sh

    - name: Run C++ Tests (Windows)
      shell: pwsh
      if: inputs.os == 'Windows'
      run: |
        ./scripts/test.ps1 -C Debug

    # TODO: build wheel first, then run the test
    - name: Run Unittests
      shell: bash
      if: inputs.os != 'Windows'
      run: |
        PYTHONPATH=src python -m unittest discover -v tests

    - name: Run Examples
      shell: bash
      if: inputs.os != 'Windows'
      run: |
        uv pip install --system -r examples/applications/requirements_applications.txt
        for example in "./examples"/*.py; do
          echo "Running $example"
          PYTHONPATH=src python $example
        done
        for example in "./examples/applications"/*.py; do
          if python -c 'import sys; sys.exit(not sys.version_info <= (3, 10))'; then
            if [ "$example" = "./examples/applications/yfinance_historical_price.py" ]; then
              echo "Skipping $example"
              continue;
            fi
          fi

          echo "Running $example"
          PYTHONPATH=src python $example
        done
